{{- if and (gt (int .Values.compactor.replicas) 1) .Values.compactor.podDisruptionBudget.enabled }}
{{ $dict := dict "ctx" . "component" "compactor" "memberlist" true }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" $dict | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" $dict | nindent 6 }}
  maxUnavailable: {{ .Values.compactor.maxUnavailable }}
{{- end }}
