apiVersion: v2
name: tempo-vulture
description: Grafana Tempo Vulture - A tool to monitor Tempo performance.
type: application
version: 0.10.0
appVersion: 2.9.0
home: https://grafana.com/docs/tempo/latest/
icon: https://raw.githubusercontent.com/grafana/tempo/master/docs/tempo/website/logo_and_name.png
sources:
  - https://github.com/grafana/tempo
maintainers:
  - name: KyriosGN0
    email: avivguiser@gmail.com
  - name: QuentinBisson
    email: quentin.bisson@gmail.com
