apiVersion: v2
appVersion: v0.38.3
description: |
  Grafana's Synthetic Monitoring application. The agent provides probe functionality and executes network checks for monitoring remote targets.

  > [!NOTE]
  > Grafana Cloud Synthetic Monitoring does not officially support this chart.
  > If you are a Grafana Cloud customer and require support, please follow the [recommended installation methods](https://grafana.com/docs/grafana-cloud/testing/synthetic-monitoring/set-up/set-up-private-probes/#deployment-with-kubernetes) listed in the public docs.
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
maintainers:
  - name: Sheikh-Abubaker
    email: sheikhabubaker761@gmail.com
  - name: KyriosGN0
    email: avivguiser@gmail.com
name: synthetic-monitoring-agent
sources:
  - https://github.com/grafana/synthetic-monitoring-agent
type: application
version: 1.2.0
